table '07 Charge'
	lineageTag: c44e85f6-917f-4452-8dc6-311f5758dcfb

	column SK_Zuora_Charge
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9d9874bb-8c03-4d10-b7d9-8999332af380
		summarizeBy: none
		sourceColumn: SK_Zuora_Charge

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Charge Number'
		dataType: string
		lineageTag: afd7bf3d-a2b2-4e77-b3fb-559b977a3f59
		summarizeBy: none
		sourceColumn: Charge Number

		annotation SummarizationSetBy = Automatic

	column 'Charge Type'
		dataType: string
		lineageTag: 403e600b-ef2a-4ab2-82b8-766e9e4da6fa
		summarizeBy: none
		sourceColumn: Charge Type

		annotation SummarizationSetBy = Automatic

	column 'Billing Period'
		dataType: string
		lineageTag: acbafb62-e31e-4afa-9919-2cd4ff9dad5d
		summarizeBy: none
		sourceColumn: Billing Period

		annotation SummarizationSetBy = Automatic

	column 'Specific Billing Period'
		dataType: int64
		formatString: 0
		lineageTag: 47324a9c-6beb-4ee8-8859-4137d92d3897
		summarizeBy: sum
		sourceColumn: Specific Billing Period

		annotation SummarizationSetBy = Automatic

	partition '07 Charge' = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"admincontrolip-production-eu" = Source{[Name="admincontrolip-production-eu"]}[Data],
				    Datamarts_Schema = #"admincontrolip-production-eu"{[Name="Datamarts",Kind="Schema"]}[Data],
				    Reporting_Dimension_Zuora_Charge_View = Datamarts_Schema{[Name="Reporting_Dimension_Zuora_Charge",Kind="View"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Reporting_Dimension_Zuora_Charge_View,{{"Charge_Type", "Charge Type"}, {"Charge_Number", "Charge Number"}, {"billing_period", "Billing Period"}, {"specific_billing_period", "Specific Billing Period"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

