table '09 Sales Type'
	lineageTag: abcdbf61-9f50-4264-912e-04bc572e2161

	column SK_Zuora_Sales_Type
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a186c406-afcb-4989-b2a7-722a3de63cde
		summarizeBy: none
		sourceColumn: SK_Zuora_Sales_Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Type'
		dataType: string
		lineageTag: c28a5de2-c8a8-40b5-9a9b-3f18edc69bd6
		summarizeBy: none
		sourceColumn: Sales Type
		sortByColumn: Custom_Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Custom_Sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f1447b8b-0b57-4d9d-bb80-03bc3a565f33
		summarizeBy: sum
		sourceColumn: Custom_Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition '09 Sales Type' = m
		mode: import
		source =
				let
				    Source = #"99 Sales Type (Old)",
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Sales_Type", "Sales Type"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

