table '99 Num Range 5-50'
	lineageTag: 045a7791-5fa8-4019-a67d-e72947877fe1

	measure 'Num Range 5-50 Value' = SELECTEDVALUE('99 Num Range 5-50'[Num Range 5-50], 10000)
		formatString: 0
		lineageTag: 10ae311a-db1c-45c8-a4a3-f44b5f3581b3

	column 'Num Range 5-50'
		formatString: 0
		lineageTag: 84a10d13-2ae7-4748-8a12-fdb647cbb5e0
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition '99 Num Range 5-50' = calculated
		mode: import
		source = GENERATESERIES(5000, 50000, 250)

	annotation PBI_Id = 7fa2fb5fc9f4404792b909ca8e0e30e6

