table Fact_ML_Mart_Churn_Prediction_Data
	isHidden
	lineageTag: 4d1d6c90-e8f1-451b-9e40-9b70a0a34ec2

	column Account_ID
		dataType: string
		isHidden
		lineageTag: 3ec229ec-2aea-42a2-ab48-9ada59a0fb9f
		summarizeBy: none
		sourceColumn: Account_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Portal_ID
		dataType: string
		isHidden
		lineageTag: 975edc0a-324f-416a-868e-97cd8bd76d39
		summarizeBy: none
		sourceColumn: Portal_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account_Type
		dataType: string
		isHidden
		lineageTag: 79870559-326e-4f68-8155-6c9fbc7dbb61
		summarizeBy: none
		sourceColumn: Account_Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column label
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 171231c3-46ed-468c-8403-5b620ecc8518
		summarizeBy: sum
		sourceColumn: label

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: eee07047-b124-47f7-a0a7-ad70fcc8c229
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		isHidden
		lineageTag: 7e68f636-5dd0-4264-a8b7-57bb860ef54d
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4a590f31-e192-4978-9915-ad72d7d9f43e
		summarizeBy: none
		sourceColumn: Date_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a0c19db1-c257-4f2f-a27b-0225ef8a4118
		summarizeBy: sum
		sourceColumn: month_index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sum_Logins
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 67dc34be-9965-4fd4-914e-7de640d89b09
		summarizeBy: sum
		sourceColumn: Sum_Logins

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Count_PortalUsers_Login
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 08fab03a-2f82-47d7-bb8b-03f14aac91fc
		summarizeBy: sum
		sourceColumn: Count_PortalUsers_Login

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sum_DocsAccessed
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c4b2f0e7-ba0e-43da-95fb-d7b6445ca7d6
		summarizeBy: sum
		sourceColumn: Sum_DocsAccessed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sum_PortalUsers_Docs
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d016d538-ee6b-4901-a109-7c3cba36efbe
		summarizeBy: sum
		sourceColumn: Sum_PortalUsers_Docs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sum_Logins_3M
		dataType: int64
		formatString: 0
		lineageTag: 3e68d65e-8be2-4f5f-a7db-5b5d3b3fe996
		summarizeBy: sum
		sourceColumn: Sum_Logins_3M

		annotation SummarizationSetBy = Automatic

	column Sum_DocsAccessed_3M
		dataType: int64
		formatString: 0
		lineageTag: c0cc2677-4406-4b43-9654-d8bd9d68744e
		summarizeBy: sum
		sourceColumn: Sum_DocsAccessed_3M

		annotation SummarizationSetBy = Automatic

	column Sum_Logins_6M
		dataType: int64
		formatString: 0
		lineageTag: 7a65f186-f148-47ea-b3ca-6a4516fd298c
		summarizeBy: sum
		sourceColumn: Sum_Logins_6M

		annotation SummarizationSetBy = Automatic

	column Sum_DocsAccessed_6M
		dataType: int64
		formatString: 0
		lineageTag: 0af760fa-36b3-4665-a111-dbd83623e30e
		summarizeBy: sum
		sourceColumn: Sum_DocsAccessed_6M

		annotation SummarizationSetBy = Automatic

	column Sum_Logins_9M
		dataType: int64
		formatString: 0
		lineageTag: b3f32d2f-daed-45ae-94e2-e176b523878f
		summarizeBy: sum
		sourceColumn: Sum_Logins_9M

		annotation SummarizationSetBy = Automatic

	column Sum_DocsAccessed_9M
		dataType: int64
		formatString: 0
		lineageTag: fd630546-29a9-49ca-ad15-f5ef7533d93b
		summarizeBy: sum
		sourceColumn: Sum_DocsAccessed_9M

		annotation SummarizationSetBy = Automatic

	column Sum_Logins_12M
		dataType: int64
		formatString: 0
		lineageTag: dc824dbf-0ca3-45d0-a07f-8de106647a6f
		summarizeBy: sum
		sourceColumn: Sum_Logins_12M

		annotation SummarizationSetBy = Automatic

	column Sum_DocsAccessed_12M
		dataType: int64
		formatString: 0
		lineageTag: b7815622-5e43-49d4-9303-588eed42b2e5
		summarizeBy: sum
		sourceColumn: Sum_DocsAccessed_12M

		annotation SummarizationSetBy = Automatic

	column DistinctLoginUsers_3M
		dataType: int64
		formatString: 0
		lineageTag: 12e25b34-1744-48ed-a3ba-f5ce09fd347e
		summarizeBy: sum
		sourceColumn: DistinctLoginUsers_3M

		annotation SummarizationSetBy = Automatic

	column DistinctLoginUsers_6M
		dataType: int64
		formatString: 0
		lineageTag: ddc15596-e60b-4e7f-8540-af7fbff91acd
		summarizeBy: sum
		sourceColumn: DistinctLoginUsers_6M

		annotation SummarizationSetBy = Automatic

	column DistinctLoginUsers_9M
		dataType: int64
		formatString: 0
		lineageTag: 83d0890a-48e5-4ecd-943c-7d52ccdcef58
		summarizeBy: sum
		sourceColumn: DistinctLoginUsers_9M

		annotation SummarizationSetBy = Automatic

	column DistinctLoginUsers_12M
		dataType: int64
		formatString: 0
		lineageTag: eccfb5a7-3817-4976-b222-bbcc99caa90e
		summarizeBy: sum
		sourceColumn: DistinctLoginUsers_12M

		annotation SummarizationSetBy = Automatic

	column DistinctDocsUsers_3M
		dataType: int64
		formatString: 0
		lineageTag: 9f304cac-721c-4448-9a10-fda0f30c838e
		summarizeBy: sum
		sourceColumn: DistinctDocsUsers_3M

		annotation SummarizationSetBy = Automatic

	column DistinctDocsUsers_6M
		dataType: int64
		formatString: 0
		lineageTag: 3ada272b-74fd-4372-b78c-0e4a72536427
		summarizeBy: sum
		sourceColumn: DistinctDocsUsers_6M

		annotation SummarizationSetBy = Automatic

	column DistinctDocsUsers_9M
		dataType: int64
		formatString: 0
		lineageTag: 80915b9e-9e19-4f91-9a47-54b0ac0338bd
		summarizeBy: sum
		sourceColumn: DistinctDocsUsers_9M

		annotation SummarizationSetBy = Automatic

	column DistinctDocsUsers_12M
		dataType: int64
		formatString: 0
		lineageTag: ea51f9b3-879f-42f4-bd0a-682ea245fe1d
		summarizeBy: sum
		sourceColumn: DistinctDocsUsers_12M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_Logins_3M
		dataType: int64
		formatString: 0
		lineageTag: 527215bd-079c-4d1e-b81c-346779c6d499
		summarizeBy: sum
		sourceColumn: prev_Sum_Logins_3M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_DocsAccessed_3M
		dataType: int64
		formatString: 0
		lineageTag: 4dde3799-634e-45b6-bacd-9c6cb1d63478
		summarizeBy: sum
		sourceColumn: prev_Sum_DocsAccessed_3M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_Logins_6M
		dataType: int64
		formatString: 0
		lineageTag: b34a81d1-03cf-4437-aeee-a7d1eb96b633
		summarizeBy: sum
		sourceColumn: prev_Sum_Logins_6M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_DocsAccessed_6M
		dataType: int64
		formatString: 0
		lineageTag: ea64bf59-09df-41d6-980d-484e9b898c57
		summarizeBy: sum
		sourceColumn: prev_Sum_DocsAccessed_6M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_Logins_9M
		dataType: int64
		formatString: 0
		lineageTag: b2ff7d4a-33a1-4360-8ac8-2c6bd2ae05cb
		summarizeBy: sum
		sourceColumn: prev_Sum_Logins_9M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_DocsAccessed_9M
		dataType: int64
		formatString: 0
		lineageTag: efb2dd00-0a7f-4a6b-94d4-c90e126b6941
		summarizeBy: sum
		sourceColumn: prev_Sum_DocsAccessed_9M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_Logins_12M
		dataType: int64
		formatString: 0
		lineageTag: 00f69218-557b-4a95-b9c5-96605fd923be
		summarizeBy: sum
		sourceColumn: prev_Sum_Logins_12M

		annotation SummarizationSetBy = Automatic

	column prev_Sum_DocsAccessed_12M
		dataType: int64
		formatString: 0
		lineageTag: 82f2255d-fbaf-4974-8ca5-d6260a60e9a6
		summarizeBy: sum
		sourceColumn: prev_Sum_DocsAccessed_12M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctLoginUsers_3M
		dataType: int64
		formatString: 0
		lineageTag: 17e5c381-64f7-4256-aad4-51a85d956fe6
		summarizeBy: sum
		sourceColumn: prev_DistinctLoginUsers_3M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctLoginUsers_6M
		dataType: int64
		formatString: 0
		lineageTag: 39aaf122-158e-4f3c-8008-90cedcf8148b
		summarizeBy: sum
		sourceColumn: prev_DistinctLoginUsers_6M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctLoginUsers_9M
		dataType: int64
		formatString: 0
		lineageTag: 2c9c1659-aa43-4046-b7ad-4869d397ed71
		summarizeBy: sum
		sourceColumn: prev_DistinctLoginUsers_9M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctLoginUsers_12M
		dataType: int64
		formatString: 0
		lineageTag: cb96d3c0-f38c-4f85-8b42-ca21cb285d4c
		summarizeBy: sum
		sourceColumn: prev_DistinctLoginUsers_12M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctDocsUsers_3M
		dataType: int64
		formatString: 0
		lineageTag: ea05cfcc-7f7b-4442-b19b-b70fe2ace165
		summarizeBy: sum
		sourceColumn: prev_DistinctDocsUsers_3M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctDocsUsers_6M
		dataType: int64
		formatString: 0
		lineageTag: 0e2ccc18-0d9b-4a51-839b-e9bb493dbe1f
		summarizeBy: sum
		sourceColumn: prev_DistinctDocsUsers_6M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctDocsUsers_9M
		dataType: int64
		formatString: 0
		lineageTag: 8c900359-3900-4ee6-a161-288be21ecb98
		summarizeBy: sum
		sourceColumn: prev_DistinctDocsUsers_9M

		annotation SummarizationSetBy = Automatic

	column prev_DistinctDocsUsers_12M
		dataType: int64
		formatString: 0
		lineageTag: 3a918950-00a1-4272-abec-ec474f2566de
		summarizeBy: sum
		sourceColumn: prev_DistinctDocsUsers_12M

		annotation SummarizationSetBy = Automatic

	partition Fact_ML_Mart_Churn_Prediction_Data = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"admincontrolip-production-eu" = Source{[Name=@BigQueryProject]}[Data],
				    Datamarts_Schema = #"admincontrolip-production-eu"{[Name="Datamarts",Kind="Schema"]}[Data],
				    Reporting_Fact_ML_Mart_Churn_Prediction_Data_View = Datamarts_Schema{[Name="Reporting_Fact_ML_Mart_Churn_Prediction_Data",Kind="View"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Reporting_Fact_ML_Mart_Churn_Prediction_Data_View,{"Owner_Country_Code", "Owner_Name"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

