table Snapshot_History
	lineageTag: e1881e70-6239-4ce9-90b6-6c3dec6ddf3e

	column Date_ID
		dataType: int64
		formatString: 0
		lineageTag: d9419036-c538-4732-b81d-3e4f9af71774
		summarizeBy: none
		sourceColumn: Date_ID

		annotation SummarizationSetBy = Automatic

	column Date_Snapshot
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4987bc0c-5c5d-46ec-92fb-f320003c6b1e
		summarizeBy: none
		sourceColumn: Date_Snapshot

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Portal Type Snapshot'
		dataType: string
		lineageTag: 017219e4-4159-4642-a441-2e5b1af63c6c
		summarizeBy: none
		sourceColumn: Portal Type Snapshot

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 32b1e2ff-fb02-4c8a-bec2-46068162eefb
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Active_Portals
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 102b8ffe-317a-41c3-8a62-b4e7f9e5a12c
		summarizeBy: sum
		sourceColumn: Active_Portals

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unique_Portal_Users
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d44a85ae-70a3-434a-a59c-a240d5c15bf6
		summarizeBy: sum
		sourceColumn: Unique_Portal_Users

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unique_Users
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d1ad3b2f-d573-4a28-9ecc-1685460ec990
		summarizeBy: sum
		sourceColumn: Unique_Users

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Snapshot_Type
		dataType: string
		lineageTag: 4a8b8135-cc84-4eef-adb1-27b29574580b
		summarizeBy: none
		sourceColumn: Snapshot_Type

		annotation SummarizationSetBy = Automatic

	column Unique_Users_2FA
		dataType: int64
		formatString: 0
		lineageTag: ab74fdd1-234e-4960-b072-764ec5fc8c34
		summarizeBy: sum
		sourceColumn: Unique_Users_2FA

		annotation SummarizationSetBy = Automatic

	column Active_Portals_2FA
		dataType: int64
		formatString: 0
		lineageTag: cceeafe5-3ab1-4237-bc3e-1f17fd09d68f
		summarizeBy: sum
		sourceColumn: Active_Portals_2FA

		annotation SummarizationSetBy = Automatic

	partition Snapshot_History = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"admincontrolip-production-eu" = Source{[Name=@BigQueryProject]}[Data],
				    Datamarts_Schema = #"admincontrolip-production-eu"{[Name="Datamarts",Kind="Schema"]}[Data],
				    Reporting_Admct_Snapshot_Portal_and_Users_View = Datamarts_Schema{[Name="Reporting_Admct_Snapshot_Portal_and_Users",Kind="View"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Reporting_Admct_Snapshot_Portal_and_Users_View,{{"Country_Code", "Country"}, {"Portal_Type", "Portal Type Snapshot"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

