table '99 BES Price'
	lineageTag: 8f8db014-246b-4e01-b475-2b6f22ae7aea

	measure 'BES Price Value' = SELECTEDVALUE('99 BES Price'[BES Price], 25000)
		formatString: 0
		lineageTag: b86c2ddc-e969-4434-8248-0a3d2ad3f73f

	column 'BES Price'
		formatString: 0
		lineageTag: b0e12178-2b2c-4734-9e61-23f63d5b8f43
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition '99 BES Price' = calculated
		mode: import
		source = GENERATESERIES(2000, 40000, 200)

	annotation PBI_Id = 31453d0ccf994f89b9770bf1887ca869

