table Portal
	lineageTag: d553a0a1-db97-4715-9f58-fc18a33fe930

	column Portal_ID
		dataType: string
		displayFolder: 02 Portal
		lineageTag: 67f28ad5-de73-4f84-ad43-ddfdf742e7a1
		summarizeBy: none
		sourceColumn: Portal_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		displayFolder: 01 Account
		lineageTag: a18b59ef-e96f-4c6e-ad70-eaf9557ca8f6
		summarizeBy: none
		sourceColumn: Account

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Vainu_Industry
		dataType: string
		displayFolder: 01 Account
		lineageTag: 286113cd-8f81-4822-a1dd-7119e9b139f5
		summarizeBy: none
		sourceColumn: Vainu_Industry

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Portal Type'
		dataType: string
		displayFolder: 02 Portal
		lineageTag: 5d88c34c-a627-4b05-9288-f705dead084b
		summarizeBy: none
		sourceColumn: Portal Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_Created
		dataType: dateTime
		formatString: General Date
		displayFolder: 02 Portal
		lineageTag: db4d5342-d596-40e7-8016-12a485514374
		summarizeBy: none
		sourceColumn: Date_Created

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CRM_Account_ID
		dataType: string
		displayFolder: 02 Portal
		lineageTag: 8c350e2e-b78b-43c8-8a43-ab07c0be04c9
		summarizeBy: none
		sourceColumn: CRM_Account_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_Purchased
		dataType: dateTime
		formatString: General Date
		displayFolder: 02 Portal
		lineageTag: 6d8f61db-1e97-49bf-9baa-a866b5be3cc3
		summarizeBy: none
		sourceColumn: Date_Purchased

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_Renewal
		dataType: dateTime
		formatString: General Date
		displayFolder: 02 Portal
		lineageTag: 4af9c6c8-4587-4350-98f8-ef42c7520b9b
		summarizeBy: none
		sourceColumn: Date_Renewal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_Closed
		dataType: dateTime
		formatString: General Date
		displayFolder: 02 Portal
		lineageTag: 34a09690-168f-4eb0-8f31-7dffca621346
		summarizeBy: none
		sourceColumn: Date_Closed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Organization_GUID
		dataType: string
		displayFolder: 02 Portal
		lineageTag: 8e6269d8-b666-4b36-87d8-3a37a5233f81
		summarizeBy: none
		sourceColumn: Organization_GUID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SK_Account
		dataType: string
		isHidden
		displayFolder: 01 Account
		lineageTag: 9912e703-67e3-4d50-81e0-f9227b1e0eaa
		summarizeBy: none
		sourceColumn: SK_Account

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Active_Portal
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal
		lineageTag: 4c512512-8bb4-49b0-b538-74c6f0ff3f14
		summarizeBy: none
		sourceColumn: Active_Portal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Demo_Portal
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal
		lineageTag: fad16232-f8eb-4b5b-bc64-b8ed77b1dbb0
		summarizeBy: none
		sourceColumn: Demo_Portal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Has_CRM_Connection
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal
		lineageTag: f6c66b6a-7010-43e8-8681-a87bcb372792
		summarizeBy: none
		sourceColumn: Has_CRM_Connection

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Licence_Fee
		dataType: int64
		formatString: 0
		displayFolder: 02 Portal
		lineageTag: 9ebb1f78-e4cd-4b5d-b7c8-fddbb3988a54
		summarizeBy: sum
		sourceColumn: Licence_Fee

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country_Code
		dataType: string
		displayFolder: 02 Portal
		lineageTag: 960d4cc6-8e7e-492e-8710-6292f15621ee
		summarizeBy: none
		sourceColumn: Country_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_Snapshot
		dataType: dateTime
		formatString: d mmmm\, yyyy
		lineageTag: c2a7f6f8-0533-4844-870a-9d8b1715bd67
		summarizeBy: none
		sourceColumn: Date_Snapshot

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Areas_Of_Use
		dataType: int64
		formatString: 0
		displayFolder: 02 Portal
		lineageTag: 2ed5e8a1-5ad5-48fa-a301-ad358db0b60c
		summarizeBy: sum
		sourceColumn: Areas_Of_Use

		annotation SummarizationSetBy = Automatic

	column Boardbook_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal\01 Features
		lineageTag: e5a1bd85-9d55-4043-94dc-0559a56aeefc
		summarizeBy: none
		sourceColumn: Boardbook_Enabled

		annotation SummarizationSetBy = Automatic

	column Electronic_Signing_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal\01 Features
		lineageTag: 3c5b251f-c496-43e0-991f-7e4fc9f6f068
		summarizeBy: none
		sourceColumn: Electronic_Signing_Enabled

		annotation SummarizationSetBy = Automatic

	column Meeting_Minutes_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal\01 Features
		lineageTag: f0cc02e9-d161-48eb-8c4a-3c71bcae43d2
		summarizeBy: none
		sourceColumn: Meeting_Minutes_Enabled

		annotation SummarizationSetBy = Automatic

	column Account_ID
		dataType: string
		displayFolder: 01 Account
		lineageTag: 77ef5537-4802-4301-aad6-18424f55e132
		summarizeBy: none
		sourceColumn: Account_ID

		annotation SummarizationSetBy = Automatic

	column Account_Type
		dataType: string
		displayFolder: 01 Account
		lineageTag: d3eb7ba6-17c5-4a75-8e8d-d9ba43f25a1c
		summarizeBy: none
		sourceColumn: Account_Type

		annotation SummarizationSetBy = Automatic

	column Account_Salesforce_Industry
		dataType: string
		displayFolder: 01 Account
		lineageTag: a22180df-49b4-47a1-83c9-1db12997a27d
		summarizeBy: none
		sourceColumn: Account_Salesforce_Industry

		annotation SummarizationSetBy = Automatic

	column Account_Number_Of_Employees
		dataType: int64
		formatString: 0
		displayFolder: 01 Account
		lineageTag: 479832d3-6876-427d-9e93-6ea5a774c00c
		summarizeBy: sum
		sourceColumn: Account_Number_Of_Employees

		annotation SummarizationSetBy = Automatic

	column Account_Board_Book_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: 48a64625-8469-43a9-877c-0d60518018ea
		summarizeBy: none
		sourceColumn: Account_Board_Book_Enabled

		annotation SummarizationSetBy = Automatic

	column Account_E_Sign_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: 535165f0-f936-4aa4-8af2-839a46d05c87
		summarizeBy: none
		sourceColumn: Account_E_Sign_Enabled

		annotation SummarizationSetBy = Automatic

	column Account_Meeting_Minutes_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: 66edd065-ddb1-453f-a0d2-8689be3de737
		summarizeBy: none
		sourceColumn: Account_Meeting_Minutes_Enabled

		annotation SummarizationSetBy = Automatic

	column Account_Secure_Messaging_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: 05634919-e1e9-489b-a91d-40a4c1b4737e
		summarizeBy: none
		sourceColumn: Account_Secure_Messaging_Enabled

		annotation SummarizationSetBy = Automatic

	column Account_CurrencyIsoCode
		dataType: string
		displayFolder: 01 Account
		lineageTag: 0e899276-0b7e-420f-b865-2a556e9657fc
		summarizeBy: none
		sourceColumn: Account_CurrencyIsoCode

		annotation SummarizationSetBy = Automatic

	column Account_Churn_Registered
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: dfd8fab4-18a4-4ac0-a0b7-6c70b49f81dc
		summarizeBy: none
		sourceColumn: Account_Churn_Registered

		annotation SummarizationSetBy = Automatic

	column Account_Billing_City
		dataType: string
		displayFolder: 01 Account
		lineageTag: d31a94e4-0c41-4560-9941-b45782d7bac1
		summarizeBy: none
		sourceColumn: Account_Billing_City

		annotation SummarizationSetBy = Automatic

	column Account_Billing_Country
		dataType: string
		displayFolder: 01 Account
		lineageTag: f5def86c-80b2-415c-9e7f-4acaf58657b5
		summarizeBy: none
		sourceColumn: Account_Billing_Country

		annotation SummarizationSetBy = Automatic

	column Account_Billing_Postal_Code
		dataType: string
		displayFolder: 01 Account
		lineageTag: baef35ac-45b3-4dac-a56c-cf024b9be7e7
		summarizeBy: none
		sourceColumn: Account_Billing_Postal_Code

		annotation SummarizationSetBy = Automatic

	column Account_Is_Deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: df4096b4-4c96-49be-8215-46e7b69ffffd
		summarizeBy: none
		sourceColumn: Account_Is_Deleted

		annotation SummarizationSetBy = Automatic

	column Vaiu_Nace
		dataType: string
		displayFolder: 01 Account
		lineageTag: a5064e11-0cab-47bf-8c12-d084a1903b34
		summarizeBy: none
		sourceColumn: Vaiu_Nace

		annotation SummarizationSetBy = Automatic

	column 'Account Owner'
		dataType: string
		displayFolder: 01.1 Account Owner
		lineageTag: 3c017dac-3102-4850-8df2-fbcab4c3163c
		summarizeBy: none
		sourceColumn: Account Owner

		annotation SummarizationSetBy = Automatic

	column Owner_Country
		dataType: string
		displayFolder: 01.1 Account Owner
		lineageTag: cc19317d-fcd0-4387-97dc-07722b5f5226
		summarizeBy: none
		sourceColumn: Owner_Country

		annotation SummarizationSetBy = Automatic

	column Owner_Country_Code
		dataType: string
		displayFolder: 01.1 Account Owner
		lineageTag: c65acf48-0d68-4434-97c5-f373c5e068a0
		summarizeBy: none
		sourceColumn: Owner_Country_Code

		annotation SummarizationSetBy = Automatic

	column Owner_Department
		dataType: string
		displayFolder: 01.1 Account Owner
		lineageTag: f52239a5-1dd2-4647-9689-b351d1298d28
		summarizeBy: none
		sourceColumn: Owner_Department

		annotation SummarizationSetBy = Automatic

	column Owner_IS_Active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01.1 Account Owner
		lineageTag: d1e7f7e1-16c7-4a8d-9c27-8432169c9f3d
		summarizeBy: none
		sourceColumn: Owner_IS_Active

		annotation SummarizationSetBy = Automatic

	column Account_Name_0
		dataType: string
		isHidden
		displayFolder: 01 Account
		lineageTag: 13a5af05-c519-442a-b996-05361757ec52
		summarizeBy: none
		sourceColumn: Account_Name_0

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account_Name_1
		dataType: string
		isHidden
		displayFolder: 01 Account
		lineageTag: 06ebbff2-28f9-40d8-aad8-c62c7cb0f533
		summarizeBy: none
		sourceColumn: Account_Name_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account_Name_2
		dataType: string
		isHidden
		displayFolder: 01 Account
		lineageTag: f7dc099c-6a8c-4732-badf-798ca65bac5b
		summarizeBy: none
		sourceColumn: Account_Name_2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account_Name_3
		dataType: string
		isHidden
		displayFolder: 01 Account
		lineageTag: bbb74eae-cda2-4c6a-b8ca-112ec4696bee
		summarizeBy: none
		sourceColumn: Account_Name_3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account_Name_4
		dataType: string
		isHidden
		displayFolder: 01 Account
		lineageTag: 5f726e93-8dc5-4e6c-90cc-90ebb3858560
		summarizeBy: none
		sourceColumn: Account_Name_4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account_Name_5
		dataType: string
		isHidden
		displayFolder: 01 Account
		lineageTag: 66c60eeb-28e6-484e-add0-abe1e4b0121a
		summarizeBy: none
		sourceColumn: Account_Name_5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Portal Name'
		dataType: string
		displayFolder: 03 SF Portal
		lineageTag: 366780d7-65a4-4dba-a98d-0e57c0859cce
		summarizeBy: none
		sourceColumn: Portal Name

		annotation SummarizationSetBy = Automatic

	column 'Is Clean Room'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 03 SF Portal
		lineageTag: 0f8d1952-6a88-4e9d-af8d-b62b30186d4a
		summarizeBy: none
		sourceColumn: Is Clean Room

		annotation SummarizationSetBy = Automatic

	column 'Sales Channel'
		dataType: string
		displayFolder: 03 SF Portal
		lineageTag: 6895816e-fad9-4dd5-97e7-66a9d318c02d
		summarizeBy: none
		sourceColumn: Sales Channel

		annotation SummarizationSetBy = Automatic

	column 'Portal Phase'
		dataType: string
		displayFolder: 03 SF Portal
		lineageTag: 048e8ec9-9c3c-475f-ac87-9e41b9bc7197
		summarizeBy: none
		sourceColumn: Portal Phase

		annotation SummarizationSetBy = Automatic

	column Portal_Live_Date
		dataType: dateTime
		formatString: Long Date
		displayFolder: 03 SF Portal
		lineageTag: 307703ae-df0c-4601-814a-a987b0f16e1f
		summarizeBy: none
		sourceColumn: Portal_Live_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Portal_Last_Login_Date
		dataType: dateTime
		formatString: d mmmm\, yyyy
		displayFolder: 03 SF Portal
		lineageTag: 2e19474e-37be-4e99-9fbd-a5371453d85c
		summarizeBy: none
		sourceColumn: Portal_Last_Login_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Account_Signed_BE_Attendum
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: d6142c3a-e3c6-4837-af18-472c9961deea
		summarizeBy: none
		sourceColumn: Account_Signed_BE_Attendum

		annotation SummarizationSetBy = Automatic

	column Days_Since_Last_Login
		dataType: int64
		formatString: 0
		lineageTag: 7a60a318-e631-46a5-8a84-14b3d8aeddc4
		summarizeBy: sum
		sourceColumn: Days_Since_Last_Login

		annotation SummarizationSetBy = Automatic

	column Account_Customer_Category
		dataType: string
		displayFolder: 01 Account
		lineageTag: 23f16bf5-1c4a-4eb4-932d-9f4cc6f6ff21
		summarizeBy: none
		sourceColumn: Account_Customer_Category

		annotation SummarizationSetBy = Automatic

	column Strategic_Customer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: ac0ee2e5-cb58-437a-a17f-a172401ffab3
		summarizeBy: none
		sourceColumn: Strategic_Customer

		annotation SummarizationSetBy = Automatic

	column Strategic_VDR_Customer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 01 Account
		lineageTag: 2d98e1bb-3442-43fd-a779-9e639636c90a
		summarizeBy: none
		sourceColumn: Strategic_VDR_Customer

		annotation SummarizationSetBy = Automatic

	column Customer_Category
		dataType: string
		displayFolder: 01 Account
		lineageTag: 2a7435ab-3c9b-496e-852a-24bc49a1e751
		summarizeBy: none
		sourceColumn: Customer_Category

		annotation SummarizationSetBy = Automatic

	column SecureMessage_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal\01 Features
		lineageTag: 1588e01f-44ee-40b1-93f9-aa5b1a01705a
		summarizeBy: none
		sourceColumn: SecureMessage_Enabled

		annotation SummarizationSetBy = Automatic

	column Annual_Plan_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal\01 Features
		lineageTag: c4479c8d-fa0b-499f-a4c8-f60ef6cd51e7
		summarizeBy: none
		sourceColumn: Annual_Plan_Enabled

		annotation SummarizationSetBy = Automatic

	column Board_Evaluation_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal\01 Features
		lineageTag: b2d8402a-a8b2-41be-8c00-f6988b8d57fd
		summarizeBy: none
		sourceColumn: Board_Evaluation_Enabled

		annotation SummarizationSetBy = Automatic

	column iOS_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal
		lineageTag: 9c696700-8f04-405c-b8be-784b0480e276
		summarizeBy: none
		sourceColumn: iOS_Enabled

		annotation SummarizationSetBy = Automatic

	column Android_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal
		lineageTag: e6545567-1791-48d1-862f-edadda9aeb75
		summarizeBy: none
		sourceColumn: Android_Enabled

		annotation SummarizationSetBy = Automatic

	column Last_Login_Android
		dataType: dateTime
		formatString: General Date
		displayFolder: Last Logins
		lineageTag: 3a33e3e5-eebe-4984-9cf7-589285369458
		summarizeBy: none
		sourceColumn: Last_Login_Android

		annotation SummarizationSetBy = Automatic

	column Last_Login_Web
		dataType: dateTime
		formatString: General Date
		displayFolder: Last Logins
		lineageTag: 1f0eb8f2-fc69-46c7-a693-deb1c4ff081f
		summarizeBy: none
		sourceColumn: Last_Login_Web

		annotation SummarizationSetBy = Automatic

	column Last_Login_iPhone
		dataType: dateTime
		formatString: General Date
		displayFolder: Last Logins
		lineageTag: 9058a0e4-f6f8-4e33-a0de-089b9201564b
		summarizeBy: none
		sourceColumn: Last_Login_iPhone

		annotation SummarizationSetBy = Automatic

	column Last_Login_iPad
		dataType: dateTime
		formatString: General Date
		displayFolder: Last Logins
		lineageTag: 32c62556-1456-4d79-9b12-bce5b81e3296
		summarizeBy: none
		sourceColumn: Last_Login_iPad

		annotation SummarizationSetBy = Automatic

	column Last_Login_App
		dataType: dateTime
		formatString: General Date
		displayFolder: Last Logins
		lineageTag: 1da6ed80-5642-4614-b909-726e7a4f7c3d
		summarizeBy: none
		sourceColumn: Last_Login_App

		annotation SummarizationSetBy = Automatic

	column Tablet_Access_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal
		lineageTag: d812f4ec-af3b-4b7d-8fd8-cb5e9951927e
		summarizeBy: none
		sourceColumn: Tablet_Access_Enabled

		annotation SummarizationSetBy = Automatic

	column Is_2FA_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: 02 Portal
		lineageTag: af6fa353-898c-4639-9f09-d3b8ca95c08e
		summarizeBy: none
		sourceColumn: Is_2FA_Enabled

		annotation SummarizationSetBy = Automatic

	column Organization_Document_Versioning_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 39b8a169-e3a3-43d2-bd5f-f832097e16a9
		summarizeBy: none
		sourceColumn: Organization_Document_Versioning_Enabled

		annotation SummarizationSetBy = Automatic

	column Organization_Voting_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2d06ea34-180a-4a43-b828-1f2e56ab904e
		summarizeBy: none
		sourceColumn: Organization_Voting_Enabled

		annotation SummarizationSetBy = Automatic

	column Organization_Decisions_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1c1ad550-c8a2-4674-bb85-67401ae97271
		summarizeBy: none
		sourceColumn: Organization_Decisions_Enabled

		annotation SummarizationSetBy = Automatic

	column First_Renewal_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4f51dc94-259f-4ead-b05a-c6df75d5fc3b
		summarizeBy: none
		sourceColumn: First_Renewal_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Last_Renewal_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa0f9e81-6830-4703-92cd-ee3a8acbb960
		summarizeBy: none
		sourceColumn: Last_Renewal_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Count_Subscriptions
		dataType: int64
		formatString: 0
		lineageTag: abcabc4d-f55e-49d8-bdb1-efcad15b96cd
		summarizeBy: sum
		sourceColumn: Count_Subscriptions

		annotation SummarizationSetBy = Automatic

	column Reading_Task_Is_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8fcfabb2-1906-449a-974b-fdfe7d4f0960
		summarizeBy: none
		sourceColumn: Reading_Task_Is_Enabled

		annotation SummarizationSetBy = Automatic

	column Upload_Task_Is_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5dd14a86-d36e-420a-8f13-adf10b5bde3e
		summarizeBy: none
		sourceColumn: Upload_Task_Is_Enabled

		annotation SummarizationSetBy = Automatic

	column Download_Package_Available
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 62caf314-ede6-4988-a5c5-93d925779a28
		summarizeBy: none
		sourceColumn: Download_Package_Available

		annotation SummarizationSetBy = Automatic

	column Download_Package_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5933bdd4-dac3-4d07-a1ee-23270b7e78eb
		summarizeBy: none
		sourceColumn: Download_Package_Enabled

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: int64
		formatString: 0
		lineageTag: 3e98244f-c823-4969-b323-b3f14ce5b998
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

	column Industry_Mapping
		dataType: string
		lineageTag: 493ec7f4-db06-4c16-aa36-7fb7b66c63aa
		summarizeBy: none
		sourceColumn: Industry_Mapping

		annotation SummarizationSetBy = Automatic

	column Earliest_Date_Contract_Signed
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1d90fbf-de1f-4343-a308-9badc90b04a4
		summarizeBy: none
		sourceColumn: Earliest_Date_Contract_Signed

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Redaction_Tool_Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d0c5ce06-6fb7-457f-a6bd-29f36d75ef36
		summarizeBy: none
		sourceColumn: Redaction_Tool_Enabled

		annotation SummarizationSetBy = Automatic

	hierarchy 'H - Country - Account'
		displayFolder: 01 Account
		lineageTag: 03eaf0f4-c849-4db1-9306-4d53439f242c

		level Country
			lineageTag: c8a72c00-0cbf-47b5-8cdc-2db641c60a2b
			column: Country_Code

		level Account
			lineageTag: 08a2d9ef-5ba3-4ca0-af88-7d46a9b448cf
			column: Account

		changedProperty = IsHidden

	hierarchy 'H - Account'
		displayFolder: 01 Account
		lineageTag: 15401ef4-18dd-4f18-8aba-c8f6ce448b41

		level 'Account 0'
			lineageTag: 1c2726f2-9d47-49a5-a15d-480eb2365492
			column: Account_Name_0

		level 'Account 1'
			lineageTag: aa551e23-947b-4e5b-abd8-3f5697c9b7b6
			column: Account_Name_1

		level 'Account 2'
			lineageTag: e803b7a2-2512-43c7-a065-461445c25808
			column: Account_Name_2

		level 'Account 3'
			lineageTag: 88cd5a13-acf5-41e1-945d-794d4135a64b
			column: Account_Name_3

		level 'Account 4'
			lineageTag: 5ea683cf-c42c-4571-8084-145fbd95ea87
			column: Account_Name_4

		level 'Account 5'
			lineageTag: 1f57a939-e82d-4fd1-8993-432c352c9373
			column: Account_Name_5

	partition Portal-16a11526-f869-4a4c-963b-e1c8f735539b = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"admincontrolip-production-eu" = Source{[Name=@BigQueryProject]}[Data],
				    Datamarts_Schema = #"admincontrolip-production-eu"{[Name="Datamarts",Kind="Schema"]}[Data],
				    Reporting_Admct_Dimension_Portal_View = Datamarts_Schema{[Name="Reporting_Admct_Dimension_Portal",Kind="View"]}[Data],
				    #"Renamed Columns1" = Table.RenameColumns(Reporting_Admct_Dimension_Portal_View,{{"Account_Name", "Account"}, {"Owner_Name", "Account Owner"}, {"Organization_Type", "Portal Type"}, {"Portal_Name", "Portal Name"}, {"Is_Clean_Room", "Is Clean Room"}, {"Portal_Phase", "Portal Phase"}, {"Sales_Channel", "Sales Channel"}, {"Organization_Annual_Plan_Enabled", "Annual_Plan_Enabled"}, {"Organization_Board_Evaluation_Enabled", "Board_Evaluation_Enabled"}, {"Organization_Boardbook_Enabled", "Boardbook_Enabled"}, {"Organization_Electronic_Signing_Enabled", "Electronic_Signing_Enabled"}, {"Organization_Meeting_Minutes_Enabled", "Meeting_Minutes_Enabled"}, {"Organization_SecureMessage_Enabled", "SecureMessage_Enabled"}, {"Organization_Android_Enabled", "Android_Enabled"}, {"Organization_iOS_Enabled", "iOS_Enabled"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

